- name: Вывод текста на сервере
  hosts: qwerty
  become: true

  tasks:
    - name: Установка зависимостей Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Добавление Docker GPG ключа
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление Docker репозитория
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Установка Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Запуск контейнера Hello World
      docker_container:
        name: hello-world
        image: hello-world
        state: started
        pull: yes
