- name: Вывод текста на сервере
  hosts: "{{ extra_host | default('ytrt') }}"
  become: true

  tasks:
    - name: Install packages
      apt:
        name:
          - docker.io
          - python3-docker
          - python3-apt
          - python3-pip
          - unattended-upgrades
        cache_valid_time: 86400

    - name: List private ip addresses from default vpcs on DO
      set_fact:
        private_ips_do: >-
          {{ ansible_all_ipv4_addresses | ipaddr("10.124.0.0/20")
          + ansible_all_ipv4_addresses | ipaddr("10.130.0.0/16")
          + ansible_all_ipv4_addresses | ipaddr("10.131.0.0/16")
          + ansible_all_ipv4_addresses | ipaddr("10.132.0.0/16")
          + ansible_all_ipv4_addresses | ipaddr("10.133.0.0/16")
          + ansible_all_ipv4_addresses | ipaddr("10.135.0.0/16")
          + ansible_all_ipv4_addresses | ipaddr("10.136.0.0/16")
          + ansible_all_ipv4_addresses | ipaddr("10.137.0.0/16")
          + ansible_all_ipv4_addresses | ipaddr("10.139.0.0/16")
          }}
    - name: debug
      debug:
        msg: ${{ private_ips_do }}
