- name: Вывод текста на сервере
  hosts: "{{ extra_host | default('ytrt') }}"
  become: true

  tasks:
    - name: Install packages
      apt:
        name:
          - docker.io
          - python3-docker
          - python3-apt
          - python3-pip
          - unattended-upgrades
        cache_valid_time: 86400

    - name: List private ip addresses from default vpcs on DO
      set_fact:
        private_ips_do: >-
          {{ ansible_all_ipv4_addresses }}

    - name: debug
      debug:
        msg: ${{ private_ips_do }}
