- name: Вывод текста на сервере
  hosts: "{{ extra_host | default('qwerty') }}"
  become: true

  tasks:
    - name: Install packages
      apt:
        name:
          - docker.io
          - python3-docker
          - python3-apt
          - python3-pip
          - unattended-upgrades
        cache_valid_time: 86400

    - name: Запуск контейнера Hello World
      docker_container:
        name: hello-world
        image: hello-world
        state: started
        pull: yes
